### ISSUE TITLE
User Mgt: "Read" actions were displayed four times even if user just uploaded a file

### ISSUE THREAD

**Issue by barbacenasmc** [barbacenasmc/armis-issues#1]
Pre-condition:
- There should be no record filed on the RM site yet.

Steps to replicate:

1. Login as an agency records officer.
2. Navigate to a record category in RM site.
3. Create a new record folder.
4. File a new record in RM site.
5. Click "Edit Metadata".
6. Fill-out the required fields and save.
7. Declare the file as record.
8. Generate a new user management report.

Actual result: Report displays "READ" actions four times.
Expected result: Report should only display "CREATE" actions.

![image](https://cloud.githubusercontent.com/assets/7791554/8846396/6618f894-3159-11e5-9522-af03f865f29f.png)

Note: Read action was saved to database whenever user lands on the record folder where the record was located. Sequence of actions based on timestamp was:
(Jul 23, 2015 16:04 01) READ ->
(Jul 23, 2015 16:04 16) updateNodeProperties 
(Jul 23, 2015 16:04 17) READ 
(Jul 23, 2015 16:04 20) updateNoteProperties 
(Jul 23, 2015 16:04 55) CREATE 
(Jul 23, 2015 16:04 57) READ 
(Jul 23, 2015 16:04 57) READ

**Comment by emarino0411** [comment]
System limitation in saving data.

**Comment by barbacenasmc** [comment]
Hi Ms. @emarino0411 , I can't produce the report. It's still corrupted though I already executed the trigger. Please see my steps on how I setup the reporting db below:
- re-create the alfrescoreporting database
- executed the additional mysql functions
- harvest reporting database
- executed the trigger
- generate the report

**Comment by barbacenasmc** [comment]
I also tried to update the report templete in alfresco explorer using the latest report template I retrieved from armis-issues github project.

**Comment by barbacenasmc** [comment]
Issue still can't be tested. Report displays no data. I found a text file in the armis_issues named -usermanagement_function_table.sql, converted it to sql and imported it to the reporting db but still no progress.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
![image](https://cloud.githubusercontent.com/assets/7791554/10931312/499fe9a8-8301-11e5-991e-c36ef78f8cef.png)
