### ISSUE TITLE
View Record Properties: Retention period is missing

### ISSUE THREAD

**Issue by barbacenasmc** [barbacenasmc/armis-issues#10]
Steps to replicate:

1. Open an existing non-electronic record to view.
2. Observe the properties section on the right side of the viewing page and look for retention period.

Actual result: Retention period is missing.

Expected result: Retention period should display.

![image](https://cloud.githubusercontent.com/assets/7791554/8819530/9ec19ff0-307f-11e5-925f-a5bede6c928a.png)

**Comment by emarino0411** [comment]
fixed

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
