### ISSUE TITLE
Record that has multiple entry in the database does not display

### ISSUE THREAD

**Issue by barbacenasmc** [barbacenasmc/armis-issues#11]
Steps to replicate:

1. File a new non-electronic record for an agency.
2. Edit the metadata and fill-out the required fields.
3. Declare the record.
4. Harvest report data to database.
5. Generate an agency or national records inventory report for non-electronic record.(Observe that the record will display)
6. Edit the metadata again and save.
7. Harvest report data to database.
8. Generate an agency or national records inventory report for non-electronic record.

Actual result: The non-electronic record no longer displays.

Expected result: The latest version of the non-electronic record should display.

![image](https://cloud.githubusercontent.com/assets/7791554/8820838/6e8f56d6-308b-11e5-8677-362ab1bf1751.png)

![image](https://cloud.githubusercontent.com/assets/7791554/8820841/72e59e7a-308b-11e5-96f3-a8d36e51d011.png)

**Comment by emarino0411** [comment]
isLatest = 0 is not the latest version. we only get the isLatest = 1.

**Comment by barbacenasmc** [comment]
Issue can no longer be replicated.
