### ISSUE TITLE
User Mgt: Sorting of entries by timestamp was not ascending

### ISSUE THREAD

**Issue by barbacenasmc** [barbacenasmc/armis-issues#12]
Steps to replicate:
1. Generate a user management report.
2.Observe the timestamp for a specific document

Actual Result: Sorting of entries by timestamp was not ascending. It wasn't also descending in order.
Expected Result: Sorting of entries by timestamp should be ascending.

![Uploading image.png…]()

**Comment by emarino0411** [comment]
Records are in order armis_agencyName,title,timestamp,userName ASC

**Comment by emarino0411** [comment]
Fixed and ready for next release

**Comment by barbacenasmc** [comment]
Retesting of this issue was blocked due to corrupted report generated.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
