### ISSUE TITLE
Document Tracking per Document: Adding of documents with the same file name is wrong

### ISSUE THREAD

**Issue by ramoscharismarie** [barbacenasmc/armis-issues#13]
Steps to replicate:
1. Go to the document tracking and choose "per document" for the Report Subtype
2. search for the document by typing a keyword 

Expected result: 
- When add button of the first of the 2 documents with the same 
file name is clicked, the second document will be added.

![document tracking edited add](https://cloud.githubusercontent.com/assets/12993604/8902519/ec10de6c-3483-11e5-8fed-d624bd2147b1.png)

Expected result: 
- The first document should be added

**Comment by emarino0411** [comment]
Fixed. for checking na lang

**Comment by barbacenasmc** [comment]
Bug fix was already verified.
