### ISSUE TITLE
Document tracking: Some documents that do not correspond to the typed keyword is still displayed

### ISSUE THREAD

**Issue by ramoscharismarie** [barbacenasmc/armis-issues#14]
Steps to replicate:
1. Go to the document tracking and choose "per document" for the Report Subtype
2. Search for the document by typing a keyword

Actual result: 
- Some documents that do not correspond to the keyword that was typed was still displayed

![document tracking edited key](https://cloud.githubusercontent.com/assets/12993604/8902620/cf5ff432-3484-11e5-8419-95b9cd473045.png)

Expected result:
- Only documents that correspond or contain the keyword should be dispayed.

**Comment by emarino0411** [comment]
fixed

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
