### ISSUE TITLE
Agency Records Inventory: Department/Division field on header displays incorrect data

### ISSUE THREAD

**Issue by barbacenasmc** [barbacenasmc/armis-issues#17]
Pre-condition:
- There should be an existing declared record in the records managment site.
- Reporting database was filled with latest data.
- Current department/division for test agency is "Agency A"

Steps to replicate:
1. Login as administrator.
2. Navigate to reports.
3. Select "Records Inventory" as report type.
4. Select "Per Agency" as report subtype.
5. Search for an existing agency and add.
6. Select "Electronic" as record type.
7. Specify period covered. (Make sure that filing date of record is included in the data range.
8. Select PDF.
9. Click "Generate"
10. Open the downloaded PDF.

Actual result: 
Department/Division field on header displays incorrect data. Field displayed "Agency A YA"

Expected result: Department/Division field should display "Agency A"
![image](https://cloud.githubusercontent.com/assets/7791554/9081021/86747b72-3b8b-11e5-8f66-9e5346fb048b.png)

**Comment by emarino0411** [comment]
Fixed Ready for next release

**Comment by barbacenasmc** [comment]
Issue can still be replicated:
![image](https://cloud.githubusercontent.com/assets/7791554/9300697/5b731518-44fb-11e5-889e-4428c56917c0.png)

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
