### ISSUE TITLE
Agency Records Admin: Available report subtype is "National" only

### ISSUE THREAD

**Issue by barbacenasmc** [barbacenasmc/armis-issues#18]
Steps to replicate:
1. Create a new site.
2. Create a new agency and select the previously created site.
3. Create a new user.
4. Invite the user to the agency site and give him a "Manager" site role.
5. Add also the user to the "AGENCY_ADMINISTRATOR" group. (This is for the user to have access the report module. Only users added in this group can access reports which are for their agency).
6. Login as the agency site manager.
7. Click "More" from the application toolbar and select "Reports".
8. Select "Records Inventory" from "Report Type".
9. Click "Report Subtype" dropdown to check options.

Actual result: Available report subtype is "National" only

Expected result: Available report subtype should be "Agency" only
![agency-admin-report-page](https://cloud.githubusercontent.com/assets/7791554/9081204/0ea10c08-3b8d-11e5-9a43-02de54cb78bd.png)

**Comment by emarino0411** [comment]
Fixed. Ready for next release.

**Comment by barbacenasmc** [comment]
Issue can still be replicated:

![image](https://cloud.githubusercontent.com/assets/7791554/9300026/74fda4b4-44f4-11e5-8219-bc44bba398a8.png)

**Comment by barbacenasmc** [comment]
Issue can still be replicated. "National" is still displayed in the list of options. It should be "Per Agency" only.

![image](https://cloud.githubusercontent.com/assets/7791554/9378503/8840212a-4754-11e5-9395-b135714c817d.png)

**Comment by emarino0411** [comment]
fixed in latest push

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
