### ISSUE TITLE
Agency Records Inventory: Period covered dates are not aligned with the report label

### ISSUE THREAD

**Issue by barbacenasmc** [barbacenasmc/armis-issues#19]
Steps to replicate:

1. Generate an agency records inventory report.
2. Observe the footer.

Actual result: Period covered dates are not aligned with the report label

Expected result: Period covered dates should be properly aligned with the report label
![agency-records-inv-footer](https://cloud.githubusercontent.com/assets/7791554/9081311/c75f53d0-3b8d-11e5-8a22-a514706ddc06.png)

**Comment by emarino0411** [comment]
Fixed. Ready for next release.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
