### ISSUE TITLE
Error message was displayed when trying to edit an agency

### ISSUE THREAD

**Issue by barbacenasmc** [barbacenasmc/armis-issues#2]
Steps to replicate:

1. Login as admin.
2. Create a new agency.
3. Edit the previously created agency.
5. Click Save.

Actual result: Error message was displayed saying
*"Failed to update the details for agency: 06160002 Wrapped Exception (with status template): 06160136 Failed to execute script 'classpath*:alfresco/templates/webscripts/org/alfresco/repository/agency/agency.put.json.js': 06160135 TypeError: Cannot find function match. (file:/home/grg021/armis_prod/prod5/webapps/alfresco/WEB-INF/classes/alfresco/templates/webscripts/org/alfresco/repository/agency/agency.put.json.js#50)."*

Expected result: Saving of agency should succeed.
![edit-agency](https://cloud.githubusercontent.com/assets/7791554/8715262/691a6008-2bb1-11e5-83c5-421eb3d4a6de.png)

**Comment by emarino0411** [comment]
Fixed. Ready for next release

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
