### ISSUE TITLE
Document Tracking Per Document does not display any result

### ISSUE THREAD

**Issue by barbacenasmc** [barbacenasmc/armis-issues#20]
Steps to replicate:

1. Login as an agency site manager.
2. Navigate to the agency site (DM site).
3. Upload a new document and assign it to a workflow.
4. Fill reporting database using Alfresco explorer.
5.  Generate a new document tracking per document report.

Actual result: PDF generated displays headers only and has no items.

Expected result: PDF generated should display a header that has a document with an outstanding task.

![image](https://cloud.githubusercontent.com/assets/7791554/9102596/d58c6a94-3c26-11e5-8bbb-abfcd6b2d121.png)

**Comment by emarino0411** [comment]
Please make sure that the date and time is within the workflow duration (see alfresco.ACT_HI_TASKINST.START_TIME ). I updated the prpt file though. Ready for next release

**Comment by barbacenasmc** [comment]
Issue can still be replicated:

![image](https://cloud.githubusercontent.com/assets/7791554/9379193/192ea724-475a-11e5-9312-c8684ecc7bfa.png)

![image](https://cloud.githubusercontent.com/assets/7791554/9379198/21c157a6-475a-11e5-89d3-51cd2fef1ade.png)

**Comment by barbacenasmc** [comment]
Hi, still I can't generate a document tracking report. Please help me identify the problem about this. I already executed the additional ARMIS functions, plus updated the prpt file on Alfresco. I already used a non-prod setup so that the database name of the app will still be "alfresco" but still no data was displayed. I can provide the dump files of the two database plus the alf data as needed.

**Comment by emarino0411** [comment]
please do not re-build your application tomorrow. will check what is the problem with your setup. thanks

**Comment by barbacenasmc** [comment]
Alright, thanks.

**Comment by barbacenasmc** [comment]
This issue can still be replicated. I reset the app, updated the prpt file on Alfresco Explorer, re-created the database and to make sure, I used 2 documents and started each in a workflow. What I only got is a task for site invitation. And this results to issue #65
![image](https://cloud.githubusercontent.com/assets/7791554/10928470/87d7e7f2-82e3-11e5-8ecb-d02a2cc65be1.png)

**Comment by barbacenasmc** [comment]
I'm closing this issue since the title is no longer valid with the situation. Please refer to issue #65 instead.
