### ISSUE TITLE
Agency Records Inventory: File size has no corresponding unit

### ISSUE THREAD

**Issue by barbacenasmc** [barbacenasmc/armis-issues#21]
Steps to replicate:

1. Generate an agency records inventory report.
2. Observe the values on the file size column.

Actual result: There was no corresponding unit.

Expected result: "MB" should be appended to the file size.

![image](https://cloud.githubusercontent.com/assets/7791554/9102974/790948c8-3c2b-11e5-8475-20752bde5cfc.png)

**Comment by emarino0411** [comment]
Fixed. Ready for next release.

**Comment by barbacenasmc** [comment]
Issue can still be replicated:
![image](https://cloud.githubusercontent.com/assets/7791554/9300618/ab5fa79a-44fa-11e5-98cf-eaa9466b4abf.png)

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
