### ISSUE TITLE
Agency Records Inventory:Lengthy agency name overlaps the time value and retention period column

### ISSUE THREAD

**Issue by barbacenasmc** [barbacenasmc/armis-issues#22]
Steps to replicate:

1. Generate an agency records inventory for an agency with a lengthy name.

Actual result: Lengthy agency name overlaps the time value and retention period column.
Expected result: Agency name should be displayed within the borders of the column.

![image](https://cloud.githubusercontent.com/assets/7791554/9103090/9becf71c-3c2c-11e5-92d7-1a8cb3ee5930.png)

**Comment by emarino0411** [comment]
Previous issue with the template.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
