### ISSUE TITLE
Agency Records Inventory: Records from a specific folder was not grouped in a single table

### ISSUE THREAD

**Issue by barbacenasmc** [barbacenasmc/armis-issues#23]
Steps to replicate:

1. As agency records officer, create 1 record folder for 2 different record category each.
2. File and declare records for the two different folders.
3. Fill reporting database using Alfresco explorer.
4. Generate a new agency records inventory report.

Actual result: Records from a specific folder was not grouped in a single table. Folder 1  and folder 2 items were displayed alternately.

Expected result: Records from a specific folder should be grouped in a single table. Then another table will be displayed for the records for another folder.

![image](https://cloud.githubusercontent.com/assets/7791554/9103266/c8abb0ac-3c2e-11e5-9f77-1c0e6b7b3315.png)

**Comment by emarino0411** [comment]
They are from a different location. See location. This is a default behaviour for pentaho. Check for the complete location. Although they have the same folder, they have the different parent folder.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
