### ISSUE TITLE
Agency Records Inventory: Only the first selected agency was displayed

### ISSUE THREAD

**Issue by barbacenasmc** [barbacenasmc/armis-issues#24]
Steps to replicate:

1. Login as administrator.
2. Navigate to reports.
3. Select "Records Inventory" as report type.
4. Select "Per Agency" as report subtype.
5. Search for multiple agencies and add.
6. Select "Electronic" as record type.
7. Specify period covered. (Make sure that filing date of record is included in the data range.
8. Select PDF.
9. Click "Generate"
10. Open the downloaded PDF.

Actual result: Only the first selected agency was displayed in the report.

Expected result: Other agencies should be displayed in the report with a separate report header.
![igovphil - admin console](https://cloud.githubusercontent.com/assets/7791554/9103369/24fa2298-3c30-11e5-9f8f-453f097d284c.png)

**Comment by emarino0411** [comment]
Allow multiple pop up windows.

**Comment by emarino0411** [comment]
Per agency is performed by doing multiple report generation.

**Comment by emarino0411** [comment]
Please check release notes on allowing multiple pop up windows.

**Comment by barbacenasmc** [comment]
Marking this issue as closed because issue was found not valid after allowing multiple pop-up.
