### ISSUE TITLE
Certificate of Disposal: Value for location of records is missing

### ISSUE THREAD

**Issue by barbacenasmc** [barbacenasmc/armis-issues#25]
Steps to replicate:

1. As agency records officer, file and declare a non-electronic record for an agency in the RM site.
2. Fill reporting database through Alfresco explorer.
3. Login as admin and generate a certificate of disposal for the previously created non-electronic record.

Actual result:  Value for location of records is missing

Expected result: Location of records should display the location of the records center of the agency.

![image](https://cloud.githubusercontent.com/assets/7791554/9107241/611532a4-3c58-11e5-97be-70bd383dd3d6.png)

**Comment by emarino0411** [comment]
Location of record depends on the declared non-electronic fields d.rma_shelf-d.rma_box-d.rma_file

**Comment by barbacenasmc** [comment]
Issue can no longer be replicated.
