### ISSUE TITLE
Certificate of Disposal: An extra agency name was displayed below the table

### ISSUE THREAD

**Issue by barbacenasmc** [barbacenasmc/armis-issues#26]
Steps to replicate:

1. As agency records officer, file and declare a non-electronic record for an agency in the RM site.
2. Fill reporting database through Alfresco explorer.
3. Login as admin and generate a certificate of disposal for the previously created non-electronic record.

Actual result: An extra agency name was displayed below the table.

Expected result: There should be no extra agency name below the table.

![image](https://cloud.githubusercontent.com/assets/7791554/9107550/9e9fd3b6-3c5a-11e5-8031-439c2249866d.png)

**Comment by emarino0411** [comment]
Fixed. Ready for next release.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
