### ISSUE TITLE
Certificate of Disposal: Fields for manual input are missing

### ISSUE THREAD

**Issue by barbacenasmc** [barbacenasmc/armis-issues#27]
Steps to replicate:

1. As agency records officer, file and declare a non-electronic record for an agency in the RM site.
2. Fill reporting database through Alfresco explorer.
3. Login as admin and generate a certificate of disposal for the previously created non-electronic record.

Actual result: Manual user input  fields- total volume, total weight, amount paid, mode of disposal, place, receipt number and date of payment as well as the names and signatures of witnesses/representatives are missing.

Expected result: Manual user input fields should be displayed.

![image](https://cloud.githubusercontent.com/assets/7791554/9107621/4a26747e-3c5b-11e5-8646-e72c969b5dcb.png)

Sample:

![image](https://cloud.githubusercontent.com/assets/7791554/9107689/dce7b02a-3c5b-11e5-9182-5c92c0912046.png)

**Comment by emarino0411** [comment]
Fixed. Ready for next release.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
