### ISSUE TITLE
Agency Records Inventory: Time Value and Retention Period does not show actual value

### ISSUE THREAD

**Issue by barbacenasmc** [barbacenasmc/armis-issues#28]
Steps to replicate:

1. Generate a new agency records inventory report.

Actual result: Time Value and Retention Period does not show actual value. Time value always displays "Permanent" while retention period always display "N/A"

Expected result: Time value should display permanent if the record has no disposition schedule or has "accession" as the last disposition action. Otherwise, if the last disposition action of the record is "destroy", it should display "temporary". Retention period should display the disposition instruction that corresponds to the last disposition action of the record. If the record is permanent, that's the only time that it will display "N/A"

![image](https://cloud.githubusercontent.com/assets/7791554/9127793/8f6524c6-3cf2-11e5-8b1b-bc07ffc8a61f.png)

**Comment by emarino0411** [comment]
For verification with sir greg

**Comment by barbacenasmc** [comment]
Hi Ms. @emarino0411 , I would like to ask the actual status of this issue right now? Thanks.

**Comment by emarino0411** [comment]
Still no idea where to get the disposition schedule. Assistance needed.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
