### ISSUE TITLE
Agency Records Inventory: Directory column displays the entire directory path of a record

### ISSUE THREAD

**Issue by barbacenasmc** [barbacenasmc/armis-issues#29]
Steps to replicate:

1. Generate an agency records inventory report.

Actual result: Directory column displays the entire directory path of a record

Expected result: Directory column should display only the record folder in which it belongs.
![image](https://cloud.githubusercontent.com/assets/7791554/9128145/eb9394ae-3cf6-11e5-8bfa-eab7239a58a9.png)

Sample:
![image](https://cloud.githubusercontent.com/assets/7791554/9128190/4a34f1d8-3cf7-11e5-9c46-a11a719eb9bb.png)

**Comment by emarino0411** [comment]
Fixed. Already implemented to other reports in records inventory agency and national (electronic and non electronic)

**Comment by barbacenasmc** [comment]
Issue can still be replicated:

![image](https://cloud.githubusercontent.com/assets/7791554/9300426/627c3414-44f8-11e5-9691-c01eec366537.png)

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
