### ISSUE TITLE
Agency records inventory: Volume field is not in the report

### ISSUE THREAD

**Issue by ramoscharismarie** [barbacenasmc/armis-issues#3]
Steps to replicate:
1. With a created site and agency with declared reports, generate a report.
2. Observe the report.

Actual result:
- File size field is displayed instead of volume.

![agency records file size edited](https://cloud.githubusercontent.com/assets/12993604/8795700/a67643fe-2fc1-11e5-8cc2-ec00a196503a.png)

Expected result:
- The volume field should be in the report.
- The volume field in the generated report should be the same as the input in the volume field when filing a record.

**Comment by emarino0411** [comment]
Volume is only available in non-electronic records only.

**Comment by barbacenasmc** [comment]
Issue logged is not valid. Expected result is incorrect.
