### ISSUE TITLE
National Records Inventory: "Generated By" field displays the agency name instead of the current user's first and last name

### ISSUE THREAD

**Issue by barbacenasmc** [barbacenasmc/armis-issues#30]
Steps to replicate:

1. Login as administrator.
2. Generate a national records inventory report.
3. Observe the generated by field.

Actual result:  "Generated By" field displays the agency name instead of the current user name

Expected result: "Generated By" field should display the current user's first and last name.

![image](https://cloud.githubusercontent.com/assets/7791554/9128284/831a5e06-3cf8-11e5-881e-4c48c5c1c4dc.png)

**Comment by emarino0411** [comment]
Done. Ready for next release

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
