### ISSUE TITLE
National Records Inventory: Directory path side borders are not connected to the main table

### ISSUE THREAD

**Issue by barbacenasmc** [barbacenasmc/armis-issues#31]
Steps to replicate:

1. Generate a national records inventory.
2. Observe the portion for directory path right below the report header.

Actual result: Directory path side borders are not connected to the main table.

Expected result: Directory path side borders should be connected to the main table.

![image](https://cloud.githubusercontent.com/assets/7791554/9128327/f83cbfda-3cf8-11e5-82a1-025ecb56b3b7.png)

**Comment by emarino0411** [comment]
Fixed ready for next release

**Comment by barbacenasmc** [comment]
Issue can still be replicated:

![image](https://cloud.githubusercontent.com/assets/7791554/9512263/17ddde82-4cb2-11e5-9276-56a152fa0b95.png)

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
