### ISSUE TITLE
National Records Inventory: Group report header was repeated even if records displayed belong to the same folder

### ISSUE THREAD

**Issue by barbacenasmc** [barbacenasmc/armis-issues#33]
Steps to replicate:

1. Generate a national records inventory report.

Actual result: Group report header was repeated even if records displayed belong to the same folder

Expected result: Group report header should be displayed once for records that belong to the same folder in a page.

![image](https://cloud.githubusercontent.com/assets/7791554/9129387/c3e36994-3d09-11e5-84ad-d237f0a71d6f.png)

**Comment by emarino0411** [comment]
Fixed by updating the path checker. Changed from cm_title to cm_name

**Comment by barbacenasmc** [comment]
Issue can no longer be replicated.
