### ISSUE TITLE
National Records Inventory: A certain page has no group report header

### ISSUE THREAD

**Issue by barbacenasmc** [barbacenasmc/armis-issues#34]
Steps to replicate: 

1. Generate a national records inventory report.

Actual result: A certain page has no group report header

Expected result: In every page, there has to be a group report header.

![image](https://cloud.githubusercontent.com/assets/7791554/9129632/d46a28ea-3d0c-11e5-8531-618bcac2974a.png)

Link to generated report: https://www.dropbox.com/s/ucg7mgn2hmi9bqu/RecordsInventoryNationalElectronic%20%282%29.pdf?dl=0

**Comment by emarino0411** [comment]
Fixed by updating the path checker from cm_title to cm_name. Ready for next release.

**Comment by barbacenasmc** [comment]
Issue can no longer be replicated.
