### ISSUE TITLE
National Records Inventory: Agency name was displayed on the remarks field

### ISSUE THREAD

**Issue by barbacenasmc** [barbacenasmc/armis-issues#35]
Steps to replicate:

1. Generate a national records inventory report.

Actual result:Agency name was displayed on the remarks field

Expected result: Remarks field should be blank.

![image](https://cloud.githubusercontent.com/assets/7791554/9130448/554d4dea-3d15-11e5-9394-4c86896d88c8.png)

**Comment by emarino0411** [comment]
Fixed. Ready for next release

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
