### ISSUE TITLE
National Records Inventory: Report header on some pages are missing

### ISSUE THREAD

**Issue by barbacenasmc** [barbacenasmc/armis-issues#36]
Steps to replicate:

1. Generate a national records inventory report.
2. Observe the report header on each page.

Actual result: Report header on some pages are missing

Expected result: There should be a report header on every page.

![image](https://cloud.githubusercontent.com/assets/7791554/9131524/dec51298-3d1e-11e5-8734-52077b10d3ec.png)

**Comment by emarino0411** [comment]
Fixed by updating the checking of agency listing. Ready for next release.

**Comment by barbacenasmc** [comment]
Issue can no longer be replicated.

**Comment by barbacenasmc** [comment]
Issue was replicated again:

![image](https://cloud.githubusercontent.com/assets/7791554/9537753/004efd7e-4d6f-11e5-9b61-118e17ac1e2c.png)

**Comment by barbacenasmc** [comment]
Issue can no longer be replicated.
