### ISSUE TITLE
Agency Records Inventory: A certain group displays no directory path

### ISSUE THREAD

**Issue by barbacenasmc** [barbacenasmc/armis-issues#37]
Steps to replicate:

1. Generate an agency records inventory.

Actual result: A certain group displays no directory path. All items within this group came from different record folders.

Expected result: All item group should display a directory path

![image](https://cloud.githubusercontent.com/assets/7791554/9241122/b54e9a2e-41a1-11e5-9e83-67d2fac74a68.png)

**Comment by emarino0411** [comment]
Fixed by updating the path checker from cm_title to cm_name

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
