### ISSUE TITLE
Agency Records Inventory: Record filed for a certain date does not display when it was used as input on date from and date end

### ISSUE THREAD

**Issue by barbacenasmc** [barbacenasmc/armis-issues#38]
Pre-condition:
- There should be filed and declared records for 2015-08-12
Steps to replicate:

1. Login as admin.
2. Go to reports.
3. Generate an agency records inventory report using 2015-08-12 for both date from and date end on the period covered fields.

Actual result: No record for the date 2015-08-12 was displayed.

Expected result: The records filed for the date 2015-08-12 should be displayed.

![image](https://cloud.githubusercontent.com/assets/7791554/9241236/4db30be6-41a3-11e5-8380-838d49bfaa34.png)

**Comment by emarino0411** [comment]
Fixed with no. 38

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
