### ISSUE TITLE
Agency Records Inventory: Record filed for a certain date does not display when it was used as input on date from

### ISSUE THREAD

**Issue by barbacenasmc** [barbacenasmc/armis-issues#39]
Pre-condition:
- There should be filed and declared records for 2015-08-12
Steps to replicate:

1. Login as admin.
2. Go to reports.
3. Generate an agency records inventory report using 2015-08-12 for date from and use 2015-08-13 date end on the period covered fields.

Actual result: No record for the date 2015-08-12 was displayed.

Expected result: The records filed for the date 2015-08-12 should be displayed.

![image](https://cloud.githubusercontent.com/assets/7791554/9241295/3bd13e38-41a4-11e5-84ac-f614809d614d.png)

**Comment by emarino0411** [comment]
Fixed. Ready for next release.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
