### ISSUE TITLE
Agency Records Inventory: Name of report and date covered is wrong

### ISSUE THREAD

**Issue by ramoscharismarie** [barbacenasmc/armis-issues#4]
Steps to replicate:
1. With an existing agency linked to a site that contains reports, generate a record.
2. Observe the generated record.

Actual result:
- Name of report is labeled as "National Records Inventory"
- Date covered is always "2010 - 2013"

![agency records footer edited](https://cloud.githubusercontent.com/assets/12993604/8795799/abe3f466-2fc2-11e5-816b-716d8f4a5fee.png)

Expected result:
- Name of report should be "Agency records inventory".
- Date covered should be depending on the start date and end date used for generating.

**Comment by emarino0411** [comment]
Fixed. Ready for release

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
