### ISSUE TITLE
Agency Records Inventory: Agency label is not aligned with the period covered on report footer

### ISSUE THREAD

**Issue by barbacenasmc** [barbacenasmc/armis-issues#40]
Steps to replicate:

1. Generate a new agency records inventory.
2. Observe the report footer.

Actual Result: Agency label is not aligned with the period covered on report footer

Expected Result: Agency label should be aligned with the period covered.
![image](https://cloud.githubusercontent.com/assets/7791554/9241571/01ffdb0c-41a8-11e5-8525-fa80cd77f10f.png)

**Comment by emarino0411** [comment]
Fixed. Ready for next release.

**Comment by barbacenasmc** [comment]
Issue can still be replicated:
![image](https://cloud.githubusercontent.com/assets/7791554/9300394/1e72f42e-44f8-11e5-9354-e3029ffc82e7.png)

**Comment by barbacenasmc** [comment]
Duplicate issue of #19 . Marking this as closed.
