### ISSUE TITLE
National Records Inventory Report: Lengthy agency name overlaps the time value and retention period column

### ISSUE THREAD

**Issue by barbacenasmc** [barbacenasmc/armis-issues#41]
Steps to replicate:

1. Generate an agency records inventory for an agency with a lengthy name.

Actual result: Lengthy agency name overlaps the time value and retention period column.
Expected result: Agency name should be displayed within the borders of the column.

![image](https://cloud.githubusercontent.com/assets/7791554/9243723/a60e215e-41c6-11e5-9078-4c02a7a7a180.png)

**Comment by emarino0411** [comment]
Fixed by using the folder name. (dating change request kasi sobrang haba)

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
