### ISSUE TITLE
National Records Inventory: First sorting rule was according to date filed instead of by agency

### ISSUE THREAD

**Issue by barbacenasmc** [barbacenasmc/armis-issues#42]
Pre-condition:
- There were filed and declared records in 3 different agencies.
Steps to replicate:

1. Generate a national records inventory report.

Actual result: First sorting rule was according to date filed instead of by agency that's why a certain agency was repeated on the other pages.

Expected result: First sorting rule should be by agency, then by folder, then by date filed.

Dropbox link to generated report - https://www.dropbox.com/s/9f99edb0lx7pnz9/RecordsInventoryNationalElectronic.pdf?dl=0

**Comment by emarino0411** [comment]
Fixed. Ready for next release.

**Comment by barbacenasmc** [comment]
Issue can no longer be replicated.
