### ISSUE TITLE
National Records Inventory: Record filed for a certain date does not display when it was used as input on date from

### ISSUE THREAD

**Issue by barbacenasmc** [barbacenasmc/armis-issues#43]
Pre-condition:
- There should be filed and declared records for 2015-08-12

Steps to replicate:

1. Login as admin.
2. Go to reports.
3. Generate an national records inventory report using 2015-08-12 for date from and use 2015-08-13 date end on the period covered fields.

Actual result: No record for the date 2015-08-12 was displayed.

Expected result: The records filed for the date 2015-08-12 should be displayed.

![screenshot](https://cloud.githubusercontent.com/assets/7791554/9245005/05cdb260-41d3-11e5-9e73-018a6c494cf5.png)

**Comment by emarino0411** [comment]
Fixed. Ready for next release

**Comment by barbacenasmc** [comment]
Issue can still be replicated.
![national-rec-inventory-date-filed-date-on-date-from](https://cloud.githubusercontent.com/assets/7791554/9513595/57b70a30-4cc4-11e5-9b22-138ff2dc5c0b.png)

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
