### ISSUE TITLE
National Records Inventory: Record filed for a certain date does not display when it was used as input on date from and date end

### ISSUE THREAD

**Issue by barbacenasmc** [barbacenasmc/armis-issues#44]
Pre-condition:
- There should be filed and declared records for 2015-08-12
Steps to replicate:

1. Login as admin.
2. Go to reports.
3. Generate an national records inventory report using 2015-08-12 for both date from and date end on the period covered fields.

Actual result: No record for the date 2015-08-12 was displayed.

Expected result: The records filed for the date 2015-08-12 should be displayed.

![screenshot](https://cloud.githubusercontent.com/assets/7791554/9245056/6f782aec-41d3-11e5-8115-59272df548bc.png)

**Comment by emarino0411** [comment]
Fixed. Ready for next release.

**Comment by barbacenasmc** [comment]
Issue can still be replicated.
![national-rec-inventory-same-date-to-from](https://cloud.githubusercontent.com/assets/7791554/9513555/f6cfee1c-4cc3-11e5-99c0-7cfc737ff362.png)

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
