### ISSUE TITLE
National Records Inventory (NE): Location of records is not aligned with the other data

### ISSUE THREAD

**Issue by barbacenasmc** [barbacenasmc/armis-issues#45]
Pre-condition:
- There should be filed and declared non-electronic records that exist.

Steps to replicate:

1. Generate a national records inventory for non electronic records.

Actual result: Location of records is not aligned with the other data

Expected result: Location of records should be aligned with the other data

![image](https://cloud.githubusercontent.com/assets/7791554/9246259/06a8d16a-41dd-11e5-9e0e-7bf67f7dd618.png)

**Comment by emarino0411** [comment]
Fixed. Updated the textfield size and alignment. Ready for next release

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
