### ISSUE TITLE
National Records Inventory (NE): Table body is not aligned with the table header

### ISSUE THREAD

**Issue by barbacenasmc** [barbacenasmc/armis-issues#46]
Steps to replicate:

1. Generate a national records inventory report for non-electronic records.

Actual result: Table body is not aligned with the table header

Expected result: Table body should be aligned with the table header
![image](https://cloud.githubusercontent.com/assets/7791554/9246318/5762b4a4-41dd-11e5-888f-3ca348e65220.png)

**Comment by emarino0411** [comment]
Fixed Ready for next release

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
