### ISSUE TITLE
Certificate of disposal produces a corrupted PDF file

### ISSUE THREAD

**Issue by barbacenasmc** [barbacenasmc/armis-issues#47]
Steps to replicate:

1. File and declare non-electronic records.
2. Generate a certificate of disposal that includes those records.

Actual result: Downloaded PDF displays no report or content at all.

Expected result: PDF should display certificate of disposal report

![image](https://cloud.githubusercontent.com/assets/7791554/9378923/e6ee3d1c-4757-11e5-895d-90f06184db44.png)

**Comment by emarino0411** [comment]
db function missing.

**Comment by barbacenasmc** [comment]
Issue can no longer be replicated.
