### ISSUE TITLE
National record inventory report produces a corrupted PDF file

### ISSUE THREAD

**Issue by barbacenasmc** [barbacenasmc/armis-issues#48]
Steps to replicate:

1. File and declare electronic records.
2. Generate a national records inventory report.

Actual result: Downloaded PDF displays no report or content at all.

Expected result: PDF should display national records inventory report.

![image](https://cloud.githubusercontent.com/assets/7791554/9378971/570c1cea-4758-11e5-98a5-2e8458306f7e.png)

**Comment by emarino0411** [comment]
Fixed in commit 6f6c8ea. Pls run all the sql functions again.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
