### ISSUE TITLE
National Records Inventory NE produces corrupted PDF

### ISSUE THREAD

**Issue by barbacenasmc** [barbacenasmc/armis-issues#49]
Steps to replicate:

1. File and declare non-electronic records.
2. Generate a national records inventory report for non-electronic records.

Actual result: Downloaded PDF displays no report or content at all.

Expected result: PDF should display national records inventory report for non-electronic records.

![image](https://cloud.githubusercontent.com/assets/7791554/9379003/b4ce8994-4758-11e5-9074-905bbc921593.png)

**Comment by emarino0411** [comment]
db function missing.

**Comment by barbacenasmc** [comment]
Issue can no longer be replicated after execution of additional mysql functions.
