### ISSUE TITLE
Agency Records Inventory: Data in the header of the generated record is wrong

### ISSUE THREAD

**Issue by ramoscharismarie** [barbacenasmc/armis-issues#5]
Steps to replicate:
1. With an existing agency linked to a site with a declared record, generate a report.
2. Observe the generated report.

Actual result:
- Data in the header is wrong

![agency a info](https://cloud.githubusercontent.com/assets/12993604/8795992/fbbb16b2-2fc3-11e5-9818-b3fd4dd3a043.PNG)
![agency records header edited](https://cloud.githubusercontent.com/assets/12993604/8795990/fb4a527e-2fc3-11e5-9031-932064a2c4e4.png)

Expected result:
- Data in the generated report should be the same as the data of the created site

**Comment by emarino0411** [comment]
Different database used.

**Comment by barbacenasmc** [comment]
Issue can no longer be replicated.
