### ISSUE TITLE
Agency Records Inventory NE:Data for location column is not aligned with the other data

### ISSUE THREAD

**Issue by barbacenasmc** [barbacenasmc/armis-issues#50]
Steps to replicate;

1. File and declare non-electronic records.
2. Generate an agency records inventory for non-electronic records.

Actual result: Data for location column is not aligned with the other data

Expected result: Data for location column should be aligned with the other data
![image](https://cloud.githubusercontent.com/assets/7791554/9379055/18fa2176-4759-11e5-8cb9-76fb53dc43c3.png)

**Comment by emarino0411** [comment]
Fixed at 3f7c199

**Comment by barbacenasmc** [comment]
Issue can no longer be replicated.
