### ISSUE TITLE
User Management Report produces corrupted PDF file

### ISSUE THREAD

**Issue by barbacenasmc** [barbacenasmc/armis-issues#51]
Steps to replicate:

1. Generate a user management report.

Actual result: Downloaded PDF displays no report or content at all.

Expected result: PDF should display user management report.

![image](https://cloud.githubusercontent.com/assets/7791554/9379329/0a7e59d0-475b-11e5-8130-d1d8567ac478.png)

**Comment by emarino0411** [comment]
db function missing.

**Comment by barbacenasmc** [comment]
Issue no longer exists.
