### ISSUE TITLE
Certificate of Disposal: Footer displays "Certificate of Disposition"

### ISSUE THREAD

**Issue by barbacenasmc** [barbacenasmc/armis-issues#52]
Steps to replicate:

1. Generate a certificate of disposal report.
2. Observe the footer of the page.

Actual result: Footer displays "Certificate of Disposition"

Expected result: Footer should display "Certificate of Disposal"

![image](https://cloud.githubusercontent.com/assets/7791554/9538779/9448d602-4d7a-11e5-9468-407033e8454f.png)

**Comment by emarino0411** [comment]
Fixed

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
