### ISSUE TITLE
Certificate of Disposal: Report subtype option displays "Certificate of Disposition"

### ISSUE THREAD

**Issue by barbacenasmc** [barbacenasmc/armis-issues#53]
Steps to replicate:

1. Login as admin.
2. Go to Reports.
3. Select "Disposition" for report type.
4. Click the list of options for report subtype.

Actual result: Report subtype option displays "Certificate of Disposition"

Expected result: Report subtype option should display "Certificate of Disposal"

![image](https://cloud.githubusercontent.com/assets/7791554/9538821/472ebcd2-4d7b-11e5-9fa7-c1c9b3b7edc6.png)

**Comment by emarino0411** [comment]
Fixed at bitbucket commit reference: ae8e0ce (for review and merging with sir @ghermo)

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
