### ISSUE TITLE
Agency Records Inventory: Retention period always displays "N/A"

### ISSUE THREAD

**Issue by ramoscharismarie** [barbacenasmc/armis-issues#6]
Steps to replicate:
1. With an existing agency linked to a site with declared records, generate a report.
2. Observe the generated report.

Actual result:
- Retention period always displays "N/A".

![agency records retention period edited](https://cloud.githubusercontent.com/assets/12993604/8796128/dd0cac3e-2fc4-11e5-9c51-e30c510879d9.png)

Expected result:
- Retention period must be the same as the input on the retention period when filing a record

**Comment by emarino0411** [comment]
Fixed. Ready for next release

**Comment by barbacenasmc** [comment]
This issue is related with issue #28 . I'm closing this issue now.
