### ISSUE TITLE
User Management Report: Record title was displayed instead of record name when using PPT file

### ISSUE THREAD

**Issue by barbacenasmc** [barbacenasmc/armis-issues#66]
Steps to replicate:

1. File and declare a PPT file to a test folder in the RM file plan.
2. Harvest reporting database.
3. Generate user management report.

Actual result: Record title was displayed instead of record name when using PPT file

Expected result: Record name should be displayed in the report.

![image](https://cloud.githubusercontent.com/assets/7791554/10931372/c1498040-8301-11e5-829f-2fff2e429288.png)

**Comment by emarino0411** [comment]
Fixed by updating trigger.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
