### ISSUE TITLE
User Management Report: Period covered and sorting rule was missing on footer

### ISSUE THREAD

**Issue by barbacenasmc** [barbacenasmc/armis-issues#67]
Steps to replicate:

1. Generate a user management report.
2. Observe the footer of the report.

Actual result: Period covered and sorting rule was missing on footer

Expected result: Period covered and sorting rule should be available on footer

![image](https://cloud.githubusercontent.com/assets/7791554/10931449/5ce2339e-8302-11e5-9e11-8af742d39348.png)

**Comment by emarino0411** [comment]
Fixed. Update prpt and bin fle.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
