### ISSUE TITLE
Document Tracking per Document: Page no. format is not consistent with other report and report type is missing on footer

### ISSUE THREAD

**Issue by barbacenasmc** [barbacenasmc/armis-issues#68]
Steps to replicate:

1. Generate a document tracking per document.
2. Observe the footer of the report.

Actual result: Page no. format is not consistent with other report and report type is missing on footer

Expected result: Page no. format should be consistent with other report and report type should be available on footer.

![image](https://cloud.githubusercontent.com/assets/7791554/10931506/d1a04b4e-8302-11e5-8934-cdf528971b42.png)

**Comment by emarino0411** [comment]
Fixed. Update bin and prpt file

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
