### ISSUE TITLE
National Records Inventory (Non-Electronic): Retention period always displays "N/A"

### ISSUE THREAD

**Issue by ramoscharismarie** [barbacenasmc/armis-issues#7]
Steps to replicate:
1. With an existing agency linked to a site with a declared record, generate a report.
2. Observe the generated report

Actual result:
- Retention period always displays "N/A"

![national records inventory retention period edited](https://cloud.githubusercontent.com/assets/12993604/8796350/b6fc4228-2fc6-11e5-8cca-a8be5c81f4b7.png)

Expected result:
- Retention period in the generated report should be the same as the retention period inputted when filing a record.

**Comment by emarino0411** [comment]
Fixed. Added rma_retentionPeriod for retention.

**Comment by barbacenasmc** [comment]
Issue can still be replicated:
![image](https://cloud.githubusercontent.com/assets/7791554/9488509/2394c0e2-4c0d-11e5-8627-1d05ad818bf2.png)

**Comment by barbacenasmc** [comment]
Issue was already fixed.
