### ISSUE TITLE
Agency Records Inventory(NE): Time value always displays "Permanent"

### ISSUE THREAD

**Issue by ramoscharismarie** [barbacenasmc/armis-issues#8]
Pre-condition:
- There should be an existing declared non-electronic record in an agency with a temporary time value.

Steps to replicate:
1. With an existing agency that is linked to a site with a declared record, generate a report.
2. Observe the generated report

Actual result:
- Time value always displays "Permanent" even if other records are labeled as "Temporary"

![image](https://cloud.githubusercontent.com/assets/7791554/8819127/d354b24c-307b-11e5-9c4b-a3c738473361.png)

![agency records time value](https://cloud.githubusercontent.com/assets/12993604/8796506/d236e9d4-2fc7-11e5-93b8-0064b495a396.png)

Expected result:
- Time value on the generated report should be the same as the time value chosen when filing a record.

**Comment by emarino0411** [comment]
Fixed. Ready for release

**Comment by barbacenasmc** [comment]
Issue can still be replicated:

![image](https://cloud.githubusercontent.com/assets/7791554/9351555/1827af92-468d-11e5-95af-14dd7d6dfdc1.png)

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
