### ISSUE TITLE
Edit Metadata: Retention period field is missing

### ISSUE THREAD

**Issue by barbacenasmc** [barbacenasmc/armis-issues#9]
Pre-condition:
- There should be an existing declared non-electronic record for an agency.
Steps to replicate:

1. Navigate to the existing non-electronic record.
2. Click "Edit Metadata"
3. Try to look for retention period field.

Actual report: Retention period field is missing

Expected report: Retention period field should be displayed after time value field.

![image](https://cloud.githubusercontent.com/assets/7791554/8819380/87d52826-307e-11e5-8f0f-2438cc451147.png)

**Comment by emarino0411** [comment]
fixed

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
